<?php
namespace ClimbUI\Imprint\GitHub;
use \Approach\Render;
	
	/**
	* This class was generated by Approach\Imprint::Mint()
	* It can be used to create a new Render tree based on the original Pattern
	*/
	class Issue extends Render\Node
	{
	public static array $tokens = [
		'Requirements','Survey','Review','Work','Describe','Adapt','Metadata'
	];
	public array $token_nodes = [];
	
	public function __construct(array $tokens = [])
	{
		$Node_0 = new Render\Node( );
	// Instantiating HTML_0__classes for upcoming classes assignment
		$HTML_0__classes = new Render\Node( );
			$HTML_0__classes[] = $Attribute_0 = new Render\Attribute( );


	// Instantiating HTML_0__attributes for upcoming attributes assignment
		$HTML_0__attributes = new Render\Attribute( );

	$Node_0[] = $HTML_0 = new Render\HTML( tag : 'div', classes: $HTML_0__classes, attributes: $HTML_0__attributes );
		// Instantiating HTML_1__classes for upcoming classes assignment
			$HTML_1__classes = new Render\Node( );
				$HTML_1__classes[] = $Attribute_2 = new Render\Attribute( );


		// Instantiating HTML_1__attributes for upcoming attributes assignment
			$HTML_1__attributes = new Render\Attribute( );

		$HTML_0[] = $HTML_1 = new Render\HTML( tag : 'h2', classes: $HTML_1__classes, attributes: $HTML_1__attributes, content : 'Body' );
		// Instantiating HTML_2__classes for upcoming classes assignment
			$HTML_2__classes = new Render\Node( );
				$HTML_2__classes[] = $Attribute_4 = new Render\Attribute( );


		// Instantiating HTML_2__attributes for upcoming attributes assignment
			$HTML_2__attributes = new Render\Attribute( );

		$HTML_0[] = $HTML_2 = new Render\HTML( tag : 'main', classes: $HTML_2__classes, attributes: $HTML_2__attributes );
			// Instantiating HTML_3__classes for upcoming classes assignment
				$HTML_3__classes = new Render\Node( );
					$HTML_3__classes[] = $Attribute_6 = new Render\Attribute( );


			// Instantiating HTML_3__attributes for upcoming attributes assignment
				$HTML_3__attributes = new Render\Attribute( );

			$HTML_2[] = $HTML_3 = new Render\HTML( tag : 'h2', classes: $HTML_3__classes, attributes: $HTML_3__attributes, content : 'Requirements' );
			// Instantiating HTML_4__classes for upcoming classes assignment
				$HTML_4__classes = new Render\Node( );
					$HTML_4__classes[] = $Attribute_8 = new Render\Attribute( );


			// Instantiating HTML_4__attributes for upcoming attributes assignment
				$HTML_4__attributes = new Render\Attribute( );

			// Instantiating HTML_4__content for upcoming content assignment
				$HTML_4__content = $this->token_nodes['Requirements'] = new Render\Token( name : 'Requirements' );

			$HTML_2[] = $HTML_4 = new Render\HTML( tag : 'details', classes: $HTML_4__classes, attributes: $HTML_4__attributes, content: $HTML_4__content );
			// Instantiating HTML_5__classes for upcoming classes assignment
				$HTML_5__classes = new Render\Node( );
					$HTML_5__classes[] = $Attribute_10 = new Render\Attribute( );


			// Instantiating HTML_5__attributes for upcoming attributes assignment
				$HTML_5__attributes = new Render\Attribute( );

			$HTML_2[] = $HTML_5 = new Render\HTML( tag : 'h2', classes: $HTML_5__classes, attributes: $HTML_5__attributes, content : 'Survey' );
			// Instantiating HTML_6__classes for upcoming classes assignment
				$HTML_6__classes = new Render\Node( );
					$HTML_6__classes[] = $Attribute_12 = new Render\Attribute( );


			// Instantiating HTML_6__attributes for upcoming attributes assignment
				$HTML_6__attributes = new Render\Attribute( );

			// Instantiating HTML_6__content for upcoming content assignment
				$HTML_6__content = $this->token_nodes['Survey'] = new Render\Token( name : 'Survey' );

			$HTML_2[] = $HTML_6 = new Render\HTML( tag : 'details', classes: $HTML_6__classes, attributes: $HTML_6__attributes, content: $HTML_6__content );
			// Instantiating HTML_7__classes for upcoming classes assignment
				$HTML_7__classes = new Render\Node( );
					$HTML_7__classes[] = $Attribute_14 = new Render\Attribute( );


			// Instantiating HTML_7__attributes for upcoming attributes assignment
				$HTML_7__attributes = new Render\Attribute( );

			$HTML_2[] = $HTML_7 = new Render\HTML( tag : 'h2', classes: $HTML_7__classes, attributes: $HTML_7__attributes, content : 'Review' );
			// Instantiating HTML_8__classes for upcoming classes assignment
				$HTML_8__classes = new Render\Node( );
					$HTML_8__classes[] = $Attribute_16 = new Render\Attribute( );


			// Instantiating HTML_8__attributes for upcoming attributes assignment
				$HTML_8__attributes = new Render\Attribute( );

			// Instantiating HTML_8__content for upcoming content assignment
				$HTML_8__content = $this->token_nodes['Review'] = new Render\Token( name : 'Review' );

			$HTML_2[] = $HTML_8 = new Render\HTML( tag : 'details', classes: $HTML_8__classes, attributes: $HTML_8__attributes, content: $HTML_8__content );
			// Instantiating HTML_9__classes for upcoming classes assignment
				$HTML_9__classes = new Render\Node( );
					$HTML_9__classes[] = $Attribute_18 = new Render\Attribute( );


			// Instantiating HTML_9__attributes for upcoming attributes assignment
				$HTML_9__attributes = new Render\Attribute( );

			$HTML_2[] = $HTML_9 = new Render\HTML( tag : 'h2', classes: $HTML_9__classes, attributes: $HTML_9__attributes, content : 'Work' );
			// Instantiating HTML_10__classes for upcoming classes assignment
				$HTML_10__classes = new Render\Node( );
					$HTML_10__classes[] = $Attribute_20 = new Render\Attribute( );


			// Instantiating HTML_10__attributes for upcoming attributes assignment
				$HTML_10__attributes = new Render\Attribute( );

			// Instantiating HTML_10__content for upcoming content assignment
				$HTML_10__content = $this->token_nodes['Work'] = new Render\Token( name : 'Work' );

			$HTML_2[] = $HTML_10 = new Render\HTML( tag : 'details', classes: $HTML_10__classes, attributes: $HTML_10__attributes, content: $HTML_10__content );
			// Instantiating HTML_11__classes for upcoming classes assignment
				$HTML_11__classes = new Render\Node( );
					$HTML_11__classes[] = $Attribute_22 = new Render\Attribute( );


			// Instantiating HTML_11__attributes for upcoming attributes assignment
				$HTML_11__attributes = new Render\Attribute( );

			$HTML_2[] = $HTML_11 = new Render\HTML( tag : 'h2', classes: $HTML_11__classes, attributes: $HTML_11__attributes, content : 'Describe' );
			// Instantiating HTML_12__classes for upcoming classes assignment
				$HTML_12__classes = new Render\Node( );
					$HTML_12__classes[] = $Attribute_24 = new Render\Attribute( );


			// Instantiating HTML_12__attributes for upcoming attributes assignment
				$HTML_12__attributes = new Render\Attribute( );

			// Instantiating HTML_12__content for upcoming content assignment
				$HTML_12__content = $this->token_nodes['Describe'] = new Render\Token( name : 'Describe' );

			$HTML_2[] = $HTML_12 = new Render\HTML( tag : 'details', classes: $HTML_12__classes, attributes: $HTML_12__attributes, content: $HTML_12__content );
			// Instantiating HTML_13__classes for upcoming classes assignment
				$HTML_13__classes = new Render\Node( );
					$HTML_13__classes[] = $Attribute_26 = new Render\Attribute( );


			// Instantiating HTML_13__attributes for upcoming attributes assignment
				$HTML_13__attributes = new Render\Attribute( );

			$HTML_2[] = $HTML_13 = new Render\HTML( tag : 'h2', classes: $HTML_13__classes, attributes: $HTML_13__attributes, content : 'Adapt' );
			// Instantiating HTML_14__classes for upcoming classes assignment
				$HTML_14__classes = new Render\Node( );
					$HTML_14__classes[] = $Attribute_28 = new Render\Attribute( );


			// Instantiating HTML_14__attributes for upcoming attributes assignment
				$HTML_14__attributes = new Render\Attribute( );

			// Instantiating HTML_14__content for upcoming content assignment
				$HTML_14__content = $this->token_nodes['Adapt'] = new Render\Token( name : 'Adapt' );

			$HTML_2[] = $HTML_14 = new Render\HTML( tag : 'details', classes: $HTML_14__classes, attributes: $HTML_14__attributes, content: $HTML_14__content );

		// Instantiating HTML_15__classes for upcoming classes assignment
			$HTML_15__classes = new Render\Node( );
				$HTML_15__classes[] = $Attribute_30 = new Render\Attribute( );


		// Instantiating HTML_15__attributes for upcoming attributes assignment
			$HTML_15__attributes = new Render\Attribute( );

		$HTML_0[] = $HTML_15 = new Render\HTML( tag : 'h2', classes: $HTML_15__classes, attributes: $HTML_15__attributes, content : 'Metadata' );
		// Instantiating HTML_16__classes for upcoming classes assignment
			$HTML_16__classes = new Render\Node( );
				$HTML_16__classes[] = $Attribute_32 = new Render\Attribute( );


		// Instantiating HTML_16__attributes for upcoming attributes assignment
			$HTML_16__attributes = new Render\Attribute( );

		// Instantiating HTML_16__content for upcoming content assignment
			$HTML_16__content = $this->token_nodes['Metadata'] = new Render\Token( name : 'Metadata' );

		$HTML_0[] = $HTML_16 = new Render\HTML( tag : 'details', classes: $HTML_16__classes, attributes: $HTML_16__attributes, content: $HTML_16__content );

		foreach($tokens as $key => $value){
			$this->token_nodes[$key]->content = $value;
		}
		$this->nodes[] = $Node_0;
	}
}
