<?php
namespace ClimbUI\Imprint\Climb;
use \ClimbUI\Render as ProjectRender;
use \Approach\Render;
	
	/**
	* This class was generated by Approach\Imprint::Mint()
	* It can be used to create a new Render tree based on the original Pattern
	*/
	class Viewer extends Render\Node
	{
	public static array $tokens = [
		'Edit','Requirements','Interests','Obstructions','Review','Progress','InterestsD','Hazards'
	];
	public array $token_nodes = [];
	
	public function __construct(array $tokens = [])
	{
		$Node_0 = new Render\Node( );
	// Instantiating HTML_0__classes for upcoming classes assignment
		$HTML_0__classes = new Render\Node( );
			$HTML_0__classes[] = $Attribute_0 = new Render\Attribute( name : 'class', content : 'ClimbUI TabsForm Interface' );


	// Instantiating HTML_0__attributes for upcoming attributes assignment
		$HTML_0__attributes = new Render\Attribute( );
			$HTML_0__attributes[] = $Attribute_0 = new Render\Attribute( name : 'class', content : 'ClimbUI TabsForm Interface' );


	// Instantiating HTML_0__content for upcoming content assignment
		$HTML_0__content = $this->token_nodes['Edit'] = new Render\Token( name : 'Edit' );

	$Node_0[] = $HTML_0 = new Render\HTML( tag : 'div', classes: $HTML_0__classes, attributes: $HTML_0__attributes, content: $HTML_0__content );
		// Instantiating HTML_1__classes for upcoming classes assignment
			$HTML_1__classes = new Render\Node( );
				$HTML_1__classes[] = $Attribute_2 = new Render\Attribute( name : 'class', content : 'TabBar InterfaceContent controls' );


		// Instantiating HTML_1__attributes for upcoming attributes assignment
			$HTML_1__attributes = new Render\Attribute( );
				$HTML_1__attributes[] = $Attribute_2 = new Render\Attribute( name : 'class', content : 'TabBar InterfaceContent controls' );


		$HTML_0[] = $HTML_1 = new Render\HTML( tag : 'nav', classes: $HTML_1__classes, attributes: $HTML_1__attributes );
			// Instantiating HTML_2__classes for upcoming classes assignment
				$HTML_2__classes = new Render\Node( );
					$HTML_2__classes[] = $Attribute_4 = new Render\Attribute( name : 'class', content : 'tabBtn control' );


			// Instantiating HTML_2__attributes for upcoming attributes assignment
				$HTML_2__attributes = new Render\Attribute( );
					$HTML_2__attributes[] = $Attribute_4 = new Render\Attribute( name : 'class', content : 'tabBtn control' );
					$HTML_2__attributes[] = $Attribute_6 = new Render\Attribute( name : 'data-role', content : 'trigger' );
					$HTML_2__attributes[] = $Attribute_7 = new Render\Attribute( name : 'data-action', content : 'tab.climb' );


			$HTML_1[] = $HTML_2 = new Render\HTML( tag : 'div', classes: $HTML_2__classes, attributes: $HTML_2__attributes, content : 'Requirements' );
				// Instantiating HTML_3__classes for upcoming classes assignment
					$HTML_3__classes = new Render\Node( );
						$HTML_3__classes[] = $Attribute_8 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				// Instantiating HTML_3__attributes for upcoming attributes assignment
					$HTML_3__attributes = new Render\Attribute( );
						$HTML_3__attributes[] = $Attribute_8 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				$HTML_2[] = $HTML_3 = new Render\HTML( tag : 'i', classes: $HTML_3__classes, attributes: $HTML_3__attributes );

			// Instantiating HTML_4__classes for upcoming classes assignment
				$HTML_4__classes = new Render\Node( );
					$HTML_4__classes[] = $Attribute_10 = new Render\Attribute( name : 'class', content : 'tabBtn control' );


			// Instantiating HTML_4__attributes for upcoming attributes assignment
				$HTML_4__attributes = new Render\Attribute( );
					$HTML_4__attributes[] = $Attribute_10 = new Render\Attribute( name : 'class', content : 'tabBtn control' );
					$HTML_4__attributes[] = $Attribute_12 = new Render\Attribute( name : 'data-role', content : 'trigger' );
					$HTML_4__attributes[] = $Attribute_13 = new Render\Attribute( name : 'data-action', content : 'tab.climb' );


			$HTML_1[] = $HTML_4 = new Render\HTML( tag : 'div', classes: $HTML_4__classes, attributes: $HTML_4__attributes, content : 'Survey' );
				// Instantiating HTML_5__classes for upcoming classes assignment
					$HTML_5__classes = new Render\Node( );
						$HTML_5__classes[] = $Attribute_14 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				// Instantiating HTML_5__attributes for upcoming attributes assignment
					$HTML_5__attributes = new Render\Attribute( );
						$HTML_5__attributes[] = $Attribute_14 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				$HTML_4[] = $HTML_5 = new Render\HTML( tag : 'i', classes: $HTML_5__classes, attributes: $HTML_5__attributes );

			// Instantiating HTML_6__classes for upcoming classes assignment
				$HTML_6__classes = new Render\Node( );
					$HTML_6__classes[] = $Attribute_16 = new Render\Attribute( name : 'class', content : 'tabBtn control' );


			// Instantiating HTML_6__attributes for upcoming attributes assignment
				$HTML_6__attributes = new Render\Attribute( );
					$HTML_6__attributes[] = $Attribute_16 = new Render\Attribute( name : 'class', content : 'tabBtn control' );
					$HTML_6__attributes[] = $Attribute_18 = new Render\Attribute( name : 'data-role', content : 'trigger' );
					$HTML_6__attributes[] = $Attribute_19 = new Render\Attribute( name : 'data-action', content : 'tab.climb' );


			$HTML_1[] = $HTML_6 = new Render\HTML( tag : 'div', classes: $HTML_6__classes, attributes: $HTML_6__attributes, content : 'Review' );
				// Instantiating HTML_7__classes for upcoming classes assignment
					$HTML_7__classes = new Render\Node( );
						$HTML_7__classes[] = $Attribute_20 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				// Instantiating HTML_7__attributes for upcoming attributes assignment
					$HTML_7__attributes = new Render\Attribute( );
						$HTML_7__attributes[] = $Attribute_20 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				$HTML_6[] = $HTML_7 = new Render\HTML( tag : 'i', classes: $HTML_7__classes, attributes: $HTML_7__attributes );

			// Instantiating HTML_8__classes for upcoming classes assignment
				$HTML_8__classes = new Render\Node( );
					$HTML_8__classes[] = $Attribute_22 = new Render\Attribute( name : 'class', content : 'tabBtn control' );


			// Instantiating HTML_8__attributes for upcoming attributes assignment
				$HTML_8__attributes = new Render\Attribute( );
					$HTML_8__attributes[] = $Attribute_22 = new Render\Attribute( name : 'class', content : 'tabBtn control' );
					$HTML_8__attributes[] = $Attribute_24 = new Render\Attribute( name : 'data-role', content : 'trigger' );
					$HTML_8__attributes[] = $Attribute_25 = new Render\Attribute( name : 'data-action', content : 'tab.climb' );


			$HTML_1[] = $HTML_8 = new Render\HTML( tag : 'div', classes: $HTML_8__classes, attributes: $HTML_8__attributes, content : 'Work' );
				// Instantiating HTML_9__classes for upcoming classes assignment
					$HTML_9__classes = new Render\Node( );
						$HTML_9__classes[] = $Attribute_26 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				// Instantiating HTML_9__attributes for upcoming attributes assignment
					$HTML_9__attributes = new Render\Attribute( );
						$HTML_9__attributes[] = $Attribute_26 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				$HTML_8[] = $HTML_9 = new Render\HTML( tag : 'i', classes: $HTML_9__classes, attributes: $HTML_9__attributes );

			// Instantiating HTML_10__classes for upcoming classes assignment
				$HTML_10__classes = new Render\Node( );
					$HTML_10__classes[] = $Attribute_28 = new Render\Attribute( name : 'class', content : 'tabBtn control' );


			// Instantiating HTML_10__attributes for upcoming attributes assignment
				$HTML_10__attributes = new Render\Attribute( );
					$HTML_10__attributes[] = $Attribute_28 = new Render\Attribute( name : 'class', content : 'tabBtn control' );
					$HTML_10__attributes[] = $Attribute_30 = new Render\Attribute( name : 'data-role', content : 'trigger' );
					$HTML_10__attributes[] = $Attribute_31 = new Render\Attribute( name : 'data-action', content : 'tab.climb' );


			$HTML_1[] = $HTML_10 = new Render\HTML( tag : 'div', classes: $HTML_10__classes, attributes: $HTML_10__attributes, content : 'Describe' );
				// Instantiating HTML_11__classes for upcoming classes assignment
					$HTML_11__classes = new Render\Node( );
						$HTML_11__classes[] = $Attribute_32 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				// Instantiating HTML_11__attributes for upcoming attributes assignment
					$HTML_11__attributes = new Render\Attribute( );
						$HTML_11__attributes[] = $Attribute_32 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				$HTML_10[] = $HTML_11 = new Render\HTML( tag : 'i', classes: $HTML_11__classes, attributes: $HTML_11__attributes );

			// Instantiating HTML_12__classes for upcoming classes assignment
				$HTML_12__classes = new Render\Node( );
					$HTML_12__classes[] = $Attribute_34 = new Render\Attribute( name : 'class', content : 'tabBtn control' );


			// Instantiating HTML_12__attributes for upcoming attributes assignment
				$HTML_12__attributes = new Render\Attribute( );
					$HTML_12__attributes[] = $Attribute_34 = new Render\Attribute( name : 'class', content : 'tabBtn control' );
					$HTML_12__attributes[] = $Attribute_36 = new Render\Attribute( name : 'data-role', content : 'trigger' );
					$HTML_12__attributes[] = $Attribute_37 = new Render\Attribute( name : 'data-action', content : 'tab.climb' );


			$HTML_1[] = $HTML_12 = new Render\HTML( tag : 'div', classes: $HTML_12__classes, attributes: $HTML_12__attributes, content : 'Adapt' );
				// Instantiating HTML_13__classes for upcoming classes assignment
					$HTML_13__classes = new Render\Node( );
						$HTML_13__classes[] = $Attribute_38 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				// Instantiating HTML_13__attributes for upcoming attributes assignment
					$HTML_13__attributes = new Render\Attribute( );
						$HTML_13__attributes[] = $Attribute_38 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-right' );


				$HTML_12[] = $HTML_13 = new Render\HTML( tag : 'i', classes: $HTML_13__classes, attributes: $HTML_13__attributes );


		// Instantiating HTML_14__classes for upcoming classes assignment
			$HTML_14__classes = new Render\Node( );
				$HTML_14__classes[] = $Attribute_40 = new Render\Attribute( name : 'class', content : 'Tabs InterfaceContent' );


		// Instantiating HTML_14__attributes for upcoming attributes assignment
			$HTML_14__attributes = new Render\Attribute( );
				$HTML_14__attributes[] = $Attribute_40 = new Render\Attribute( name : 'class', content : 'Tabs InterfaceContent' );


		$HTML_0[] = $HTML_14 = new Render\HTML( tag : 'main', classes: $HTML_14__classes, attributes: $HTML_14__attributes );
			// Instantiating HTML_15__classes for upcoming classes assignment
				$HTML_15__classes = new Render\Node( );
					$HTML_15__classes[] = $Attribute_42 = new Render\Attribute( name : 'class', content : 'tab active' );


			// Instantiating HTML_15__attributes for upcoming attributes assignment
				$HTML_15__attributes = new Render\Attribute( );
					$HTML_15__attributes[] = $Attribute_42 = new Render\Attribute( name : 'class', content : 'tab active' );


			// Instantiating HTML_15__content for upcoming content assignment
				$HTML_15__content = $this->token_nodes['Requirements'] = new Render\Token( name : 'Requirements' );

			$HTML_14[] = $HTML_15 = new Render\HTML( tag : 'div', classes: $HTML_15__classes, attributes: $HTML_15__attributes, content: $HTML_15__content );
			// Instantiating HTML_16__classes for upcoming classes assignment
				$HTML_16__classes = new Render\Node( );
					$HTML_16__classes[] = $Attribute_44 = new Render\Attribute( name : 'class', content : 'tab' );


			// Instantiating HTML_16__attributes for upcoming attributes assignment
				$HTML_16__attributes = new Render\Attribute( );
					$HTML_16__attributes[] = $Attribute_44 = new Render\Attribute( name : 'class', content : 'tab' );


			$HTML_14[] = $HTML_16 = new Render\HTML( tag : 'div', classes: $HTML_16__classes, attributes: $HTML_16__attributes );
				// Instantiating HTML_17__classes for upcoming classes assignment
					$HTML_17__classes = new Render\Node( );

				// Instantiating HTML_17__attributes for upcoming attributes assignment
					$HTML_17__attributes = new Render\Attribute( );

				$HTML_16[] = $HTML_17 = new Render\HTML( tag : 'h3', classes: $HTML_17__classes, attributes: $HTML_17__attributes, content : '🔍️ Survey' );
				// Instantiating HTML_18__classes for upcoming classes assignment
					$HTML_18__classes = new Render\Node( );

				// Instantiating HTML_18__attributes for upcoming attributes assignment
					$HTML_18__attributes = new Render\Attribute( );

				$HTML_16[] = $HTML_18 = new Render\HTML( tag : 'h5', classes: $HTML_18__classes, attributes: $HTML_18__attributes, content : 'Interests' );
				// Instantiating HTML_19__classes for upcoming classes assignment
					$HTML_19__classes = new Render\Node( );

				// Instantiating HTML_19__attributes for upcoming attributes assignment
					$HTML_19__attributes = new Render\Attribute( );

				// Instantiating HTML_19__content for upcoming content assignment
					$HTML_19__content = $this->token_nodes['Interests'] = new Render\Token( name : 'Interests' );

				$HTML_16[] = $HTML_19 = new Render\HTML( tag : 'div', classes: $HTML_19__classes, attributes: $HTML_19__attributes, content: $HTML_19__content );
				// Instantiating HTML_20__classes for upcoming classes assignment
					$HTML_20__classes = new Render\Node( );

				// Instantiating HTML_20__attributes for upcoming attributes assignment
					$HTML_20__attributes = new Render\Attribute( );

				$HTML_16[] = $HTML_20 = new Render\HTML( tag : 'h5', classes: $HTML_20__classes, attributes: $HTML_20__attributes, content : 'Obstructions' );
				// Instantiating HTML_21__classes for upcoming classes assignment
					$HTML_21__classes = new Render\Node( );

				// Instantiating HTML_21__attributes for upcoming attributes assignment
					$HTML_21__attributes = new Render\Attribute( );

				// Instantiating HTML_21__content for upcoming content assignment
					$HTML_21__content = $this->token_nodes['Obstructions'] = new Render\Token( name : 'Obstructions' );

				$HTML_16[] = $HTML_21 = new Render\HTML( tag : 'div', classes: $HTML_21__classes, attributes: $HTML_21__attributes, content: $HTML_21__content );

			// Instantiating HTML_22__classes for upcoming classes assignment
				$HTML_22__classes = new Render\Node( );
					$HTML_22__classes[] = $Attribute_51 = new Render\Attribute( name : 'class', content : 'tab' );


			// Instantiating HTML_22__attributes for upcoming attributes assignment
				$HTML_22__attributes = new Render\Attribute( );
					$HTML_22__attributes[] = $Attribute_51 = new Render\Attribute( name : 'class', content : 'tab' );


			// Instantiating HTML_22__content for upcoming content assignment
				$HTML_22__content = $this->token_nodes['Review'] = new Render\Token( name : 'Review' );

			$HTML_14[] = $HTML_22 = new Render\HTML( tag : 'div', classes: $HTML_22__classes, attributes: $HTML_22__attributes, content: $HTML_22__content );
				// Instantiating HTML_23__classes for upcoming classes assignment
					$HTML_23__classes = new Render\Node( );
						$HTML_23__classes[] = $Attribute_53 = new Render\Attribute( name : 'class', content : 'fs-4 fw-bold' );


				// Instantiating HTML_23__attributes for upcoming attributes assignment
					$HTML_23__attributes = new Render\Attribute( );
						$HTML_23__attributes[] = $Attribute_53 = new Render\Attribute( name : 'class', content : 'fs-4 fw-bold' );


				$HTML_22[] = $HTML_23 = new Render\HTML( tag : 'h3', classes: $HTML_23__classes, attributes: $HTML_23__attributes, content : 'Plan' );

			// Instantiating HTML_24__classes for upcoming classes assignment
				$HTML_24__classes = new Render\Node( );
					$HTML_24__classes[] = $Attribute_55 = new Render\Attribute( name : 'class', content : 'tab' );


			// Instantiating HTML_24__attributes for upcoming attributes assignment
				$HTML_24__attributes = new Render\Attribute( );
					$HTML_24__attributes[] = $Attribute_55 = new Render\Attribute( name : 'class', content : 'tab' );


			// Instantiating HTML_24__content for upcoming content assignment
				$HTML_24__content = $this->token_nodes['Progress'] = new Render\Token( name : 'Progress' );

			$HTML_14[] = $HTML_24 = new Render\HTML( tag : 'div', classes: $HTML_24__classes, attributes: $HTML_24__attributes, content: $HTML_24__content );
				// Instantiating HTML_25__classes for upcoming classes assignment
					$HTML_25__classes = new Render\Node( );

				// Instantiating HTML_25__attributes for upcoming attributes assignment
					$HTML_25__attributes = new Render\Attribute( );

				$HTML_24[] = $HTML_25 = new Render\HTML( tag : 'h3', classes: $HTML_25__classes, attributes: $HTML_25__attributes, content : '🏗️ Work' );
				// Instantiating HTML_26__classes for upcoming classes assignment
					$HTML_26__classes = new Render\Node( );

				// Instantiating HTML_26__attributes for upcoming attributes assignment
					$HTML_26__attributes = new Render\Attribute( );

				$HTML_24[] = $HTML_26 = new Render\HTML( tag : 'h5', classes: $HTML_26__classes, attributes: $HTML_26__attributes, content : 'Document Progress' );

			// Instantiating HTML_27__classes for upcoming classes assignment
				$HTML_27__classes = new Render\Node( );
					$HTML_27__classes[] = $Attribute_59 = new Render\Attribute( name : 'class', content : 'tab' );


			// Instantiating HTML_27__attributes for upcoming attributes assignment
				$HTML_27__attributes = new Render\Attribute( );
					$HTML_27__attributes[] = $Attribute_59 = new Render\Attribute( name : 'class', content : 'tab' );


			$HTML_14[] = $HTML_27 = new Render\HTML( tag : 'div', classes: $HTML_27__classes, attributes: $HTML_27__attributes );
				// Instantiating HTML_28__classes for upcoming classes assignment
					$HTML_28__classes = new Render\Node( );

				// Instantiating HTML_28__attributes for upcoming attributes assignment
					$HTML_28__attributes = new Render\Attribute( );

				$HTML_27[] = $HTML_28 = new Render\HTML( tag : 'h3', classes: $HTML_28__classes, attributes: $HTML_28__attributes, content : '📔 Describe' );
				// Instantiating HTML_29__classes for upcoming classes assignment
					$HTML_29__classes = new Render\Node( );

				// Instantiating HTML_29__attributes for upcoming attributes assignment
					$HTML_29__attributes = new Render\Attribute( );

				$HTML_27[] = $HTML_29 = new Render\HTML( tag : 'h5', classes: $HTML_29__classes, attributes: $HTML_29__attributes, content : 'Interests' );
				// Instantiating HTML_30__classes for upcoming classes assignment
					$HTML_30__classes = new Render\Node( );

				// Instantiating HTML_30__attributes for upcoming attributes assignment
					$HTML_30__attributes = new Render\Attribute( );

				// Instantiating HTML_30__content for upcoming content assignment
					$HTML_30__content = $this->token_nodes['InterestsD'] = new Render\Token( name : 'InterestsD' );

				$HTML_27[] = $HTML_30 = new Render\HTML( tag : 'div', classes: $HTML_30__classes, attributes: $HTML_30__attributes, content: $HTML_30__content );
				// Instantiating HTML_31__classes for upcoming classes assignment
					$HTML_31__classes = new Render\Node( );

				// Instantiating HTML_31__attributes for upcoming attributes assignment
					$HTML_31__attributes = new Render\Attribute( );

				$HTML_27[] = $HTML_31 = new Render\HTML( tag : 'h5', classes: $HTML_31__classes, attributes: $HTML_31__attributes, content : 'Hazards' );
				// Instantiating HTML_32__classes for upcoming classes assignment
					$HTML_32__classes = new Render\Node( );

				// Instantiating HTML_32__attributes for upcoming attributes assignment
					$HTML_32__attributes = new Render\Attribute( );

				// Instantiating HTML_32__content for upcoming content assignment
					$HTML_32__content = $this->token_nodes['Hazards'] = new Render\Token( name : 'Hazards' );

				$HTML_27[] = $HTML_32 = new Render\HTML( tag : 'div', classes: $HTML_32__classes, attributes: $HTML_32__attributes, content: $HTML_32__content );

			// Instantiating HTML_33__classes for upcoming classes assignment
				$HTML_33__classes = new Render\Node( );
					$HTML_33__classes[] = $Attribute_66 = new Render\Attribute( name : 'class', content : 'tab tab6 controls' );


			// Instantiating HTML_33__attributes for upcoming attributes assignment
				$HTML_33__attributes = new Render\Attribute( );
					$HTML_33__attributes[] = $Attribute_66 = new Render\Attribute( name : 'class', content : 'tab tab6 controls' );


			$HTML_14[] = $HTML_33 = new Render\HTML( tag : 'div', classes: $HTML_33__classes, attributes: $HTML_33__attributes );
				// Instantiating HTML_34__classes for upcoming classes assignment
					$HTML_34__classes = new Render\Node( );
						$HTML_34__classes[] = $Attribute_68 = new Render\Attribute( name : 'class', content : 'pb-2 fw-bolder' );


				// Instantiating HTML_34__attributes for upcoming attributes assignment
					$HTML_34__attributes = new Render\Attribute( );
						$HTML_34__attributes[] = $Attribute_68 = new Render\Attribute( name : 'class', content : 'pb-2 fw-bolder' );


				$HTML_33[] = $HTML_34 = new Render\HTML( tag : 'h4', classes: $HTML_34__classes, attributes: $HTML_34__attributes, content : '6. Adapt from Findings' );
				// Instantiating HTML_35__classes for upcoming classes assignment
					$HTML_35__classes = new Render\Node( );

				// Instantiating HTML_35__attributes for upcoming attributes assignment
					$HTML_35__attributes = new Render\Attribute( );

				$HTML_33[] = $HTML_35 = new Render\HTML( tag : 'p', classes: $HTML_35__classes, attributes: $HTML_35__attributes, content : 'Adapt from the findings' );
					// Instantiating HTML_36__classes for upcoming classes assignment
						$HTML_36__classes = new Render\Node( );
							$HTML_36__classes[] = $Attribute_71 = new Render\Attribute( name : 'class', content : 'fw-bolder' );


					// Instantiating HTML_36__attributes for upcoming attributes assignment
						$HTML_36__attributes = new Render\Attribute( );
							$HTML_36__attributes[] = $Attribute_71 = new Render\Attribute( name : 'class', content : 'fw-bolder' );


					$HTML_35[] = $HTML_36 = new Render\HTML( tag : 'span', classes: $HTML_36__classes, attributes: $HTML_36__attributes, content : '🦎 Adapt:' );

				// Instantiating HTML_37__classes for upcoming classes assignment
					$HTML_37__classes = new Render\Node( );
						$HTML_37__classes[] = $Attribute_73 = new Render\Attribute( name : 'class', content : 'btn-group btn-group-lg' );


				// Instantiating HTML_37__attributes for upcoming attributes assignment
					$HTML_37__attributes = new Render\Attribute( );
						$HTML_37__attributes[] = $Attribute_73 = new Render\Attribute( name : 'class', content : 'btn-group btn-group-lg' );
						$HTML_37__attributes[] = $Attribute_75 = new Render\Attribute( name : 'role', content : 'group' );
						$HTML_37__attributes[] = $Attribute_76 = new Render\Attribute( name : 'aria-label', content : 'Basic mixed styles example' );


				$HTML_33[] = $HTML_37 = new Render\HTML( tag : 'div', classes: $HTML_37__classes, attributes: $HTML_37__attributes );
					// Instantiating HTML_38__classes for upcoming classes assignment
						$HTML_38__classes = new Render\Node( );
							$HTML_38__classes[] = $Attribute_77 = new Render\Attribute( name : 'class', content : 'btn btn-warning' );


					// Instantiating HTML_38__attributes for upcoming attributes assignment
						$HTML_38__attributes = new Render\Attribute( );
							$HTML_38__attributes[] = $Attribute_79 = new Render\Attribute( name : 'type', content : 'button' );
							$HTML_38__attributes[] = $Attribute_77 = new Render\Attribute( name : 'class', content : 'btn btn-warning' );


					$HTML_37[] = $HTML_38 = new Render\HTML( tag : 'button', classes: $HTML_38__classes, attributes: $HTML_38__attributes, content : 'Iterate' );
						// Instantiating HTML_39__classes for upcoming classes assignment
							$HTML_39__classes = new Render\Node( );
								$HTML_39__classes[] = $Attribute_80 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-repeat' );


						// Instantiating HTML_39__attributes for upcoming attributes assignment
							$HTML_39__attributes = new Render\Attribute( );
								$HTML_39__attributes[] = $Attribute_80 = new Render\Attribute( name : 'class', content : 'bi bi-arrow-repeat' );


						$HTML_38[] = $HTML_39 = new Render\HTML( tag : 'i', classes: $HTML_39__classes, attributes: $HTML_39__attributes );

					// Instantiating HTML_40__classes for upcoming classes assignment
						$HTML_40__classes = new Render\Node( );
							$HTML_40__classes[] = $Attribute_82 = new Render\Attribute( name : 'class', content : 'btn btn-success' );


					// Instantiating HTML_40__attributes for upcoming attributes assignment
						$HTML_40__attributes = new Render\Attribute( );
							$HTML_40__attributes[] = $Attribute_84 = new Render\Attribute( name : 'type', content : 'button' );
							$HTML_40__attributes[] = $Attribute_82 = new Render\Attribute( name : 'class', content : 'btn btn-success' );


					$HTML_37[] = $HTML_40 = new Render\HTML( tag : 'button', classes: $HTML_40__classes, attributes: $HTML_40__attributes, content : 'Branch' );
						// Instantiating HTML_41__classes for upcoming classes assignment
							$HTML_41__classes = new Render\Node( );
								$HTML_41__classes[] = $Attribute_85 = new Render\Attribute( name : 'class', content : 'bi bi-signpost-split' );


						// Instantiating HTML_41__attributes for upcoming attributes assignment
							$HTML_41__attributes = new Render\Attribute( );
								$HTML_41__attributes[] = $Attribute_85 = new Render\Attribute( name : 'class', content : 'bi bi-signpost-split' );


						$HTML_40[] = $HTML_41 = new Render\HTML( tag : 'i', classes: $HTML_41__classes, attributes: $HTML_41__attributes );







		foreach($tokens as $key => $value){
			$this->token_nodes[$key]->content = $tokens[$key];
		}
		$this->nodes[] = $Node_0;
	}
}
