<?php
namespace ClimbUI\Imprint\Settings;
use \ClimbUI\Render as ProjectRender;
use \Approach\Render;
	
	/**
	* This class was generated by Approach\Imprint::Mint()
	* It can be used to create a new Render tree based on the original Pattern
	*/
	class Settings extends Render\Node
	{
	public static array $tokens = [
		'GITHUB_API_KEY','CLIMBSUI_OWNER','CLIMBSUI_REPO','Save'
	];
	public array $token_nodes = [];
	
	public function __construct(array $tokens = [])
	{
		$Node_0 = new Render\Node( );
	// Instantiating HTML_0__classes for upcoming classes assignment
		$HTML_0__classes = new Render\Node( );
			$HTML_0__classes[] = $Attribute_0 = new Render\Attribute( name : 'class', content : 'ClimbUI Interface InterfaceContent' );


	// Instantiating HTML_0__attributes for upcoming attributes assignment
		$HTML_0__attributes = new Render\Attribute( );
			$HTML_0__attributes[] = $Attribute_0 = new Render\Attribute( name : 'class', content : 'ClimbUI Interface InterfaceContent' );


	$Node_0[] = $HTML_0 = new Render\HTML( tag : 'div', classes: $HTML_0__classes, attributes: $HTML_0__attributes );
		// Instantiating HTML_1__classes for upcoming classes assignment
			$HTML_1__classes = new Render\Node( );

		// Instantiating HTML_1__attributes for upcoming attributes assignment
			$HTML_1__attributes = new Render\Attribute( );

		$HTML_0[] = $HTML_1 = new Render\HTML( tag : 'h1', classes: $HTML_1__classes, attributes: $HTML_1__attributes, content : 'Settings' );
		// Instantiating HTML_2__classes for upcoming classes assignment
			$HTML_2__classes = new Render\Node( );
				$HTML_2__classes[] = $Attribute_3 = new Render\Attribute( name : 'class', content : 'Autoform' );


		// Instantiating HTML_2__attributes for upcoming attributes assignment
			$HTML_2__attributes = new Render\Attribute( );
				$HTML_2__attributes[] = $Attribute_3 = new Render\Attribute( name : 'class', content : 'Autoform' );
				$HTML_2__attributes[] = $Attribute_5 = new Render\Attribute( name : 'data-action', content : 'Settings' );


		$HTML_0[] = $HTML_2 = new Render\HTML( tag : 'form', classes: $HTML_2__classes, attributes: $HTML_2__attributes );
			// Instantiating HTML_3__classes for upcoming classes assignment
				$HTML_3__classes = new Render\Node( );
					$HTML_3__classes[] = $Attribute_6 = new Render\Attribute( name : 'class', content : 'setting' );


			// Instantiating HTML_3__attributes for upcoming attributes assignment
				$HTML_3__attributes = new Render\Attribute( );
					$HTML_3__attributes[] = $Attribute_6 = new Render\Attribute( name : 'class', content : 'setting' );


			// Instantiating HTML_3__content for upcoming content assignment
				$HTML_3__content = $this->token_nodes['GITHUB_API_KEY'] = new Render\Token( name : 'GITHUB_API_KEY' );

			$HTML_2[] = $HTML_3 = new Render\HTML( tag : 'div', classes: $HTML_3__classes, attributes: $HTML_3__attributes, content: $HTML_3__content );
				// Instantiating HTML_4__classes for upcoming classes assignment
					$HTML_4__classes = new Render\Node( );

				// Instantiating HTML_4__attributes for upcoming attributes assignment
					$HTML_4__attributes = new Render\Attribute( );
						$HTML_4__attributes[] = $Attribute_9 = new Render\Attribute( name : 'for', content : 'GITHUB_API_KEY' );


				$HTML_3[] = $HTML_4 = new Render\HTML( tag : 'label', classes: $HTML_4__classes, attributes: $HTML_4__attributes, content : 'Github API Key' );

			// Instantiating HTML_5__classes for upcoming classes assignment
				$HTML_5__classes = new Render\Node( );
					$HTML_5__classes[] = $Attribute_10 = new Render\Attribute( name : 'class', content : 'setting' );


			// Instantiating HTML_5__attributes for upcoming attributes assignment
				$HTML_5__attributes = new Render\Attribute( );
					$HTML_5__attributes[] = $Attribute_10 = new Render\Attribute( name : 'class', content : 'setting' );


			// Instantiating HTML_5__content for upcoming content assignment
				$HTML_5__content = $this->token_nodes['CLIMBSUI_OWNER'] = new Render\Token( name : 'CLIMBSUI_OWNER' );

			$HTML_2[] = $HTML_5 = new Render\HTML( tag : 'div', classes: $HTML_5__classes, attributes: $HTML_5__attributes, content: $HTML_5__content );
				// Instantiating HTML_6__classes for upcoming classes assignment
					$HTML_6__classes = new Render\Node( );

				// Instantiating HTML_6__attributes for upcoming attributes assignment
					$HTML_6__attributes = new Render\Attribute( );
						$HTML_6__attributes[] = $Attribute_13 = new Render\Attribute( name : 'for', content : 'CLIMBSUI_OWNER' );


				$HTML_5[] = $HTML_6 = new Render\HTML( tag : 'label', classes: $HTML_6__classes, attributes: $HTML_6__attributes, content : 'Owner' );

			// Instantiating HTML_7__classes for upcoming classes assignment
				$HTML_7__classes = new Render\Node( );
					$HTML_7__classes[] = $Attribute_14 = new Render\Attribute( name : 'class', content : 'setting' );


			// Instantiating HTML_7__attributes for upcoming attributes assignment
				$HTML_7__attributes = new Render\Attribute( );
					$HTML_7__attributes[] = $Attribute_14 = new Render\Attribute( name : 'class', content : 'setting' );


			// Instantiating HTML_7__content for upcoming content assignment
				$HTML_7__content = $this->token_nodes['CLIMBSUI_REPO'] = new Render\Token( name : 'CLIMBSUI_REPO' );

			$HTML_2[] = $HTML_7 = new Render\HTML( tag : 'div', classes: $HTML_7__classes, attributes: $HTML_7__attributes, content: $HTML_7__content );
				// Instantiating HTML_8__classes for upcoming classes assignment
					$HTML_8__classes = new Render\Node( );

				// Instantiating HTML_8__attributes for upcoming attributes assignment
					$HTML_8__attributes = new Render\Attribute( );
						$HTML_8__attributes[] = $Attribute_17 = new Render\Attribute( name : 'for', content : 'CLIMBSUI_REPO' );


				$HTML_7[] = $HTML_8 = new Render\HTML( tag : 'label', classes: $HTML_8__classes, attributes: $HTML_8__attributes, content : 'Repo' );

			// Instantiating HTML_9__classes for upcoming classes assignment
				$HTML_9__classes = new Render\Node( );
					$HTML_9__classes[] = $Attribute_18 = new Render\Attribute( name : 'class', content : 'controls' );


			// Instantiating HTML_9__attributes for upcoming attributes assignment
				$HTML_9__attributes = new Render\Attribute( );
					$HTML_9__attributes[] = $Attribute_18 = new Render\Attribute( name : 'class', content : 'controls' );


			// Instantiating HTML_9__content for upcoming content assignment
				$HTML_9__content = $this->token_nodes['Save'] = new Render\Token( name : 'Save' );

			$HTML_2[] = $HTML_9 = new Render\HTML( tag : 'div', classes: $HTML_9__classes, attributes: $HTML_9__attributes, content: $HTML_9__content );




		foreach($tokens as $key => $value){
			$this->token_nodes[$key]->content = $tokens[$key] ?? '';
		}
		$this->nodes[] = $Node_0;
	}
}
